version: '3'

services:
  front:
    build: ./front
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./front/.env
    environment:
      REACT_APP_HOST_BACK: http://localhost:8080
    networks:
      - front-tier
    links:
      - back

  back:
    build: ./back
    restart: always
    ports:
    - "8080:80"
    environment:
      HOST_DB: db
    networks:
      - back-tier
      - front-tier

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
  front-tier:
    driver: bridge

volumes:
  db-data:
